name: Deployment-Infra-DEV-$(Rev:rr)
trigger: 
  branches:
    include:
      - main

variables:
   - group: britops-development

pool:
  vmImage: 'windows-latest'

stages:
- stage: DeployInfrastructure
  jobs:
   - job: terraform_apply_develop
     steps:
       - template: '../templates/terraform.yaml'

