name: Deployment-App-DEV-$(Rev:rr)
resources:
  pipelines:
  - pipeline: create_infrastructure
    source: CreateInfrastructure
    trigger: true

variables:
   - group: britops-development

pool: 
  vmImage: 'windows-latest'


stages:
- stage: BuildAndDeployApp
  jobs:
   - job: build_deploy
     steps:
       - template: '../templates/build.yaml'
       - template: '../templates/deploy.yaml'

       



 