location                = "northeurope"
storage_account_name    = "britopsstoragedev"
resource_group_name     = "britops-rg-dev"
function_app_plan_name  = "britops-funcappservice-dev"
function_app_name       = "britops-dev"
tag                     = "britops-dev"